# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Physx2D_config = debug
  SandBox_config = debug

else ifeq ($(config),release)
  Physx2D_config = release
  SandBox_config = release

else ifeq ($(config),dist)
  Physx2D_config = dist
  SandBox_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Physx2D SandBox

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Physx2D:
ifneq (,$(Physx2D_config))
	@echo "==== Building Physx2D ($(Physx2D_config)) ===="
	@${MAKE} --no-print-directory -C Physx2D -f Makefile config=$(Physx2D_config)
endif

SandBox:
ifneq (,$(SandBox_config))
	@echo "==== Building SandBox ($(SandBox_config)) ===="
	@${MAKE} --no-print-directory -C SandBox -f Makefile config=$(SandBox_config)
endif

clean:
	@${MAKE} --no-print-directory -C Physx2D -f Makefile clean
	@${MAKE} --no-print-directory -C SandBox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Physx2D"
	@echo "   SandBox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"